### ISSUE TITLE
70% of time wrong tmdb (imdb) info

### ISSUE THREAD

**Issue by Saman24** [filebot/scripts#44]
Hello

Thanks a lot for "artwork.tmdb" script but i don't know why it always take wrong movie info from tmdb?
this happens especially for new movies

for example:

Everlasting.2016.1080p.WEB-DL.AAC2.0.H264
Taken.Heart.2017.1080p.WEB-DL.DD5.1.H264
Another.Yeti.a.Love.Story.Life.on.the.Streets.2017.1080p.WEB-DL.AAC2.0.H264
The.Abduction.of.Jennifer.Grayson.2017.1080p.WEB-DL.AAC2.0.H264

filebot -script fn:artwork.tmdb -non-strict C:\Users\User\Desktop\new\movies

will be

Love Everlasting (2016)
Taken (2008)
Another (2014)
The Abduction of Jennifer Grayson (2017)

Only "The Abduction of Jennifer Grayson (2017)" info is correct on this list

i don't know why this script confused, this is really simple there is not some movie title on the same year

**Comment by rednoah** [comment]
The `artwork.tmdb` scripts expects your files to be well-organized:
https://support.plex.tv/hc/en-us/articles/200381023-Naming-Movie-files

i.e. `Everlasting.2016.1080p.WEB-DL.AAC2.0.H264` should be `Everlasting (2016)`

**Comment by Saman24** [comment]
Thanks for reply
but what is the point of automation script if we have to rename all movies manually?

**Comment by rednoah** [comment]
It works like this:

* Step 1: Automatically organize files properly
* Step 2: Automatically fetch artwork for properly organized files

The `artwork.*` scripts are used internally in the `amc` script which seems to work quite well for a large number of people:
https://www.filebot.net/forums/viewtopic.php?f=4&t=215

Of course, files like `Taken.Heart.2017.1080p.WEB-DL.DD5.1.H264` won't work because that movie hasn't even been added yet to TheMovieDB, so it can't be processed.

**Comment by Saman24** [comment]
Thanks
but the problem is I don't want to rename my files
there is a reason for this

e.g: 
If I rename `Everlasting.2016.1080p.WEB-DL.AAC2.0.H264` to `Everlasting (2016)`
and i decision to watch this movie 2 month later. I forget if it was `WEB-DL` or `Webrip` or `Bluray`
Sometimes even release group is important for me e.g : `Everlasting.2016.1080p.WEB-DL.AAC2.0.H264-**HDQualityGroup**`
so in short i want all these details (1080p or 720p WEB-DL or HDrip DTS or AAC) on my filename

is there any way to make it work without renaming the files and folders?

**Comment by rednoah** [comment]
No. The artwork script can't work if it can't easily know the TheMovieID for each file.

You can use FileBot to process the files, but how you want them named is up to you. Using a format such as `{ny}/{ny} {vf} {source} {ac} {channels} {vc}`.

Note that `Everlasting (2016)` doesn't work because the year is wrong (according to TheMovieDB).
