### ISSUE TITLE
Groovy and passing a mount path

### ISSUE THREAD

**Issue by kotowick** [filebot/scripts#49]
Hey there,

Running into an issue with amc.groovy.

Background:
- using Ubuntu on VM Workstation
- Ubuntu mounts a drive from the host (under /mnt/..
- when running the amc.groovy, I point it to the mount directory. I get multiple errors.. related to it thinking that the "mount" path is not a directory or file.

Assuming this issue is related to groovy not detecting the mount path as a directory..?

**Comment by rednoah** [comment]
Please copy and paste the error message.

Please read this and include additional system information:
https://www.filebot.net/forums/viewtopic.php?f=5&t=1868

**Comment by elstevega** [comment]
Can confirm; seeing the same behavior - however I do not believe the problem is with the .groovy script - I have two Ubuntu installations that are identical with the exception of the version of filebot - 4.7.5 runs correctly, 4.7.9 returns the error mentioned above. Permissions on the /mnt and subsequent directories are identical...

 filebot -script fn:sysinfo

FileBot 4.7.9 (r4986)
JNA Native: 5.1.0
MediaInfo: 0.7.82
7-Zip-JBinding: 9.20
Chromaprint: 1.2.0
Extended Attributes: OK
Unicode Filesystem: OK
Script Bundle: 2017-11-21 (r512)
Groovy: 2.4.10
JRE: OpenJDK Runtime Environment 1.8.0_121
JVM: 64-bit OpenJDK 64-Bit Server VM
CPU/MEM: 4 Core / 875 MB Max Memory / 28 MB Used Memory
OS: Linux (amd64)
Package: SNAP
uname: Linux TorrentBox 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Done ã¾(ï¼ âã¼âï¼ )ã

COMMAND LINE:

ARG_PATH="$TR_TORRENT_DIR/$TR_TORRENT_NAME"
ARG_NAME="$TR_TORRENT_NAME"
ARB_LABEL="N/A"
CONFIG_OUTPUT="/mnt/hgfs/MediaServer/iTunes Media/"

/snap/bin/filebot -script fn:amc --output "$CONFIG_OUTPUT" -no-xattr --log-file amc.log --action duplicate --conflict skip -non-strict --def music=n artwork=n ut_dir="$ARG_PATH" ut_kind="multi" ut_title="$ARG_NAME" ut_label="$ARG_LABEL"

**Comment by rednoah** [comment]
What is the console output of your Transmission script that calls FileBot?
https://www.filebot.net/forums/viewtopic.php?f=4&t=3067

If you're trying to access `/mnt` from a SNAP app then that can't work. SNAP applications are running with reduced permissions and can only access certain files. Here's more information for how to get around this issue:
https://www.filebot.net/forums/viewtopic.php?f=11&t=5139

**Comment by elstevega** [comment]
Def a Snap app issue. Thanks for the prompt and accurate response!

On Jan 24, 2018 8:01 AM, "Reinhard Pointner" <notifications@github.com>
wrote:

What is the console output of your Transmission script that calls FileBot?
https://www.filebot.net/forums/viewtopic.php?f=4&t=3067

If you're trying to access /mnt from a SNAP app then that can't work. SNAP
applications are running with reduced permissions and can only access
certain files. Here's more information for how to get around this issue:
https://www.filebot.net/forums/viewtopic.php?f=11&t=5139

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/filebot/scripts/issues/49#issuecomment-360124338>, or mute
the thread
