### ISSUE TITLE
Don't exit with 100 status code in amc if no files are found

### ISSUE THREAD

**Issue by danielcompton** [filebot/scripts#55]
In https://github.com/filebot/scripts/commit/18bcc76eb7d38737713048df79ab722eb90d69c1 this line was changed:

https://github.com/filebot/scripts/blob/a921ac570e6e0d1a07899e4c8fe738f10636711e/amc.groovy#L299-L302

Previously it exited with status 0, and now it exits with status 100.

Exiting with a non-zero status code tells my Synology that execution failed and it notifies me about it. If there are no files selected for processing, this doesn't seem like an exceptional situation? At least in my situation of running a scheduled task, it would be much more useful if it continued to exit with a zero status code unless there truly was an error. What are your thoughts?

**Comment by rednoah** [comment]
`4.8.5` has different error codes for different errors. Running the amc script on an input folder where there is nothing to do can be considered an error, or it cannot, depending on the use case and what might be convenient for the end user at the time.

`0` indicates a success run, while `100` indicates that nothing happened successfully.

Since your problem is specific to Synology Scheduler, I recommend a solution specific to Synology Scheduler.

Just add this to the end of your scheduled task:
```
STATUS=$?
# treat ExitCode.NOOP as ExitCode.SUCCESS
if [ $STATUS -eq 100 ]; then
	exit 0
fi
exit $STATUS
```

If you're using FileBot Node, then that'll be default for scheduled tasks:
https://github.com/filebot/filebot-node/blob/master/package/synology/bin/task#L14
